global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-application'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['coordinator-service:8080', 'worker-service:8081']
