spring:
  application:
    name: mergesort-worker

  kafka:
    bootstrap-servers: kafka-service:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: merge-sort-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always

info:
  app:
    name: MergeSort Service
    description: Microservice for performing merge sort operations
    version: 1.0.0
    maintainer: alejsant75@gmail.com
