server:
  port: 8080

spring:
  application:
    name: api-gateway

    gateway:
      routes:
        - id: coordinator-route
          uri: lb://coordinator-service
          predicates:
            - Path=/coordinator/**
          filters:
            - StripPrefix=1

  discovery:
    enabled: true
    client:
      serviceUrl:
        defaultZone: http://eureka-server:8761/eureka/
      registerWithEureka: true
      fetchRegistry: true
