spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Alejo2075/distributed-algorithms
          search-paths: config
          clone-on-start: true
          default-label: main
