spring:
  application:
    name: merge-sort-service

  # Server
  server:
    port: 8080

  # Redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: merge-sort-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 15000
        heartbeat.interval.ms: 3000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


# Actuator endpoints configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, conditions, configprops, env, loggers, metrics, mappings
  endpoint:
    health:
      show-details: always

info:
  app:
    name: MergeSort Service
    description: Microservice for performing merge sort operations
    version: 1.0.0
    maintainer: alejsant75@gmail.com